name: Android Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setting gradlew properties
        run: chmod +x ./AndroMate/gradlew
        
      - name: Run Tests
        run: cd AndroMate && ./gradlew test

      - name: Build Project
        run: cd AndroMate && ./gradlew assemble
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: chmod +x ./AndroMate/gradlew && cd AndroMate && ./gradlew connectedCheck
